In [1]:
from __future__ import print_function
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.optimizers import SGD
from keras.utils import np_utils



Using TensorFlow backend.


In [12]:

np.random.seed(1671)  # for reproducibility

# network and training
NB_EPOCH = 20
BATCH_SIZE = 128
VERBOSE = 1
NB_CLASSES = 10   # number of outputs = number of digits
OPTIMIZER = SGD() # SGD optimizer, explained later in this chapter
N_HIDDEN = 128
VALIDATION_SPLIT=0.2 # how much TRAIN is reserved for VALIDATION



# Downloading online data ( images matrix )

In [3]:
# data: shuffled and split between train and test sets
#
(X_train, y_train), (X_test, y_test) = mnist.load_data()



In [4]:
X_train.shape

(60000, 28, 28)

In [5]:
#X_train is 60000 rows of 28x28 values --> reshaped in 60000 x 784
RESHAPED = 784
#
X_train = X_train.reshape(60000, RESHAPED)
X_test = X_test.reshape(10000, RESHAPED)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')



In [6]:

# normalize 
#
X_train /= 255
X_test /= 255
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')



60000 train samples
10000 test samples


In [7]:
print(y_train)

[5 0 4 ... 5 6 8]


# ONE HOT ENCODING

In [8]:
# convert class vectors to binary class matrices
Y_train = np_utils.to_categorical(y_train, NB_CLASSES)
Y_test = np_utils.to_categorical(y_test, NB_CLASSES)



In [9]:
print(Y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


# DEFINING MODEL

In [15]:
# 10 outputs
# final stage is softmax

model = Sequential()

# Add an input layer 
model.add(Dense(N_HIDDEN, input_shape=(RESHAPED,)))
model.add(Activation('relu'))

#model.add(Dense(N_HIDDEN))
#model.add(Activation('relu'))

# Output layer
model.add(Dense(NB_CLASSES))
model.add(Activation('softmax'))

model.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 128)               100480    
_________________________________________________________________
activation_4 (Activation)    (None, 128)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 10)                1290      
_________________________________________________________________
activation_5 (Activation)    (None, 10)                0         
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.compile(loss='categorical_crossentropy',
              optimizer=OPTIMIZER,
              metrics=['categorical_accuracy'])



# TRAINING MODEL

In [20]:
history = model.fit(X_train, Y_train,
                    batch_size=BATCH_SIZE, epochs=NB_EPOCH,
                    verbose=VERBOSE, validation_split=VALIDATION_SPLIT)


Train on 48000 samples, validate on 12000 samples
Epoch 1/20
48000/48000 [==============================] - 2s 49us/step - loss: 0.2408 - categorical_accuracy: 0.9323 - val_loss: 0.2316 - val_categorical_accuracy: 0.9347
Epoch 2/20
48000/48000 [==============================] - 1s 31us/step - loss: 0.2363 - categorical_accuracy: 0.9336 - val_loss: 0.2280 - val_categorical_accuracy: 0.9366
Epoch 3/20
48000/48000 [==============================] - 1s 30us/step - loss: 0.2320 - categorical_accuracy: 0.9349 - val_loss: 0.2246 - val_categorical_accuracy: 0.9375
Epoch 4/20
48000/48000 [==============================] - 1s 31us/step - loss: 0.2279 - categorical_accuracy: 0.9362 - val_loss: 0.2211 - val_categorical_accuracy: 0.9393
Epoch 5/20
48000/48000 [==============================] - 1s 30us/step - loss: 0.2240 - categorical_accuracy: 0.9372 - val_loss: 0.2177 - val_categorical_accuracy: 0.9396
Epoch 6/20
48000/48000 [==============================] - 1s 31us/step - loss: 0.2202 - categor

# Model Performance [ Accuracy ]

In [21]:
score = model.evaluate(X_test, Y_test, verbose=VERBOSE)
#print("\nTest score:", score[0])
print('Test accuracy:', score[1])

10000/10000 [==============================] - 0s 35us/step
Test accuracy: 0.9474
